[project]
name = "beta-tool"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "python-dateutil>=2.9.0.post0",
    "statsmodels>=0.15.0",
    "yfinance>=1.7.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.3",
    "pytest>=9.1.1",
]
